# Generated by Django 2.2.5 on 2021-02-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='is_delete',
        ),
    ]
