# Generated by Django 2.2.5 on 2021-02-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210226_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='pub_date',
            field=models.TimeField(null=True),
        ),
    ]
