# Generated by Django 2.2.5 on 2021-02-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookinfo_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
