# Generated by Django 2.2.5 on 2021-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bookinfo_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
