# Generated by Django 2.2.5 on 2021-02-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookinfo_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='comment_count',
            new_name='commentcount',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='read_count',
            new_name='readcount',
        ),
    ]
